export { default as Achievements } from './works/works'
export { default as Footer } from './footer/Footer'
export { default as Hero } from './hero/Hero'
export { default as AboutNCC } from './about/index'
export { default as SocialMedias } from './SocialMedias/Socialmediacontainer'
export {default as Gallery } from './Gallery/index'
export {default as ProgramSection} from './Programs/index'